/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.itson.classroom.ui;

import com.itson.classroom.entities.Assigment;
import com.itson.classroom.persistence.AssigmentDAO;
import com.itson.classroom.ui.NewAssigmentForm;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author zBook
 */
public class AssigmentList extends javax.swing.JFrame {

    /**
     * Creates new form AssigmentList
     */
    public AssigmentList() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblAssigment = new javax.swing.JTable();
        btnCreate = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tblAssigment.setBackground(new java.awt.Color(204, 255, 204));
        tblAssigment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Tittle", "Description", "Due Date"
            }
        ));
        tblAssigment.setGridColor(new java.awt.Color(153, 255, 153));
        tblAssigment.setSelectionBackground(new java.awt.Color(153, 255, 153));
        tblAssigment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAssigmentMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblAssigment);

        btnCreate.setBackground(new java.awt.Color(153, 255, 102));
        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(153, 255, 102));
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(153, 255, 102));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(btnDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(btnEdit)
                        .addGap(43, 43, 43)
                        .addComponent(btnCreate)
                        .addGap(142, 142, 142)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreate)
                    .addComponent(btnEdit)
                    .addComponent(btnDelete))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        loadTableAssigments();
        tblAssigment.removeColumn(tblAssigment.getColumnModel().getColumn(0));

    }//GEN-LAST:event_formWindowOpened

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        NewAssigmentForm form = new NewAssigmentForm(this, true, 0);
        form.setVisible(true);
        
        loadTableAssigments();
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
    int selectedRow = tblAssigment.getSelectedRow();
    
    if (selectedRow != -1) {
        int idAssigment = (int) tblAssigment.getModel().getValueAt(selectedRow, 0);
        Assigment assigment = AssigmentDAO.getById(idAssigment);
            if (assigment != null) {
                NewAssigmentForm form = new NewAssigmentForm(this, true, idAssigment);
                form.setVisible(true);
                loadTableAssigments(); // Recargar después de cerrar el form
            }
        } else {
            JOptionPane.showMessageDialog(this,
                    "Debes seleccionar una actividad para editar.",
                    "Advertencia",
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void tblAssigmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAssigmentMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblAssigmentMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int selectedRow = tblAssigment.getSelectedRow();
    
        if (selectedRow != -1) {
                int idAssigment = (int) tblAssigment.getModel().getValueAt(selectedRow, 0);

                int opcion = JOptionPane.showConfirmDialog(this,
                        "¿Estás seguro que deseas eliminar esta actividad?",
                        "Confirmar eliminación",
                        JOptionPane.YES_NO_OPTION);

                if (opcion == JOptionPane.YES_OPTION) {
                    Assigment assigment = AssigmentDAO.getById(idAssigment);

                    if (assigment != null && AssigmentDAO.delete(assigment)) {
                        JOptionPane.showMessageDialog(this,
                                "Actividad eliminada correctamente.",
                                "Eliminado",
                                JOptionPane.INFORMATION_MESSAGE);
                        loadTableAssigments(); // Recargar tabla
                    } else {
                        JOptionPane.showMessageDialog(this,
                                "No se pudo eliminar la actividad.",
                                "Error",
                                JOptionPane.ERROR_MESSAGE);
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this,
                        "Debes seleccionar una actividad para eliminar.",
                        "Advertencia",
                        JOptionPane.WARNING_MESSAGE);
            }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void loadTableAssigments() {
    List<Assigment> assigments = AssigmentDAO.getAll();
    DefaultTableModel tableModel = (DefaultTableModel) tblAssigment.getModel();
    tableModel.setRowCount(0);
    for (Assigment a : assigments) {
        tableModel.addRow(new Object[]{
            a.getId(),
            a.getTittle(),
            a.getDescription(),
            a.getDue_date(),
            });
        }
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AssigmentList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AssigmentList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AssigmentList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AssigmentList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AssigmentList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAssigment;
    // End of variables declaration//GEN-END:variables
}
